sudo:  required
services: 
  - docker

before_install: 
  - docker build -t tharaka/docker-react -f Dockerfile.dev .

script: 
  - docker run tharaka/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-170483427314"
  bucket_path: "docker-react"
  on:
    branch: master
  